pluginManagement {
    repositories {
        mavenCentral()
        google()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            url 'https://dl.google.com/'
            name 'dlGoogle'
        }
        maven { url "https://jitpack.io" }
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            url 'https://dl.google.com/'
            name 'dlGoogle'
        }
        maven {
            url 'https://mvnrepository.com/artifact/com.android.tools.lint/lint-gradle-api'
        }
    }
}
rootProject.name = "SmokeDigression"
include ':app'
